import mdx from "@mdx-js/rollup";
import tailwindcss from "@tailwindcss/vite";
import { voidReact } from "@void/react/plugin";
import { defineConfig } from "vite-plus";
import { voidPlugin } from "void";
import mdxOptions from "void-blog/mdx";
import { voidBlog } from "void-blog/vite";
import blogConfig from "./blog.config.ts";

const optimizedDeps = [
  "@nkzw/stack",
  "@void/react",
  "react",
  "react-dom",
  "react-error-boundary",
  "react/jsx-dev-runtime",
  "react/jsx-runtime",
  "void/pages-client",
  "void/pages-prefetch",
  "void-blog/react",
];

const legacyIgnorePatterns = [
  "node_modules",
  "dist",
  ".wrangler",
  ".void",
  "public",
  "blog",
  "blog.bak",
  "legacy.bak",
  "MOVE",
  "movement.js",
  "max_new_space_size",
  "libuv",
  "*.html",
  "*.htm",
  "*.bak",
  "*.swf",
  "*.mp3",
  "*.png",
  "*.bash",
  "atom-apps-list.md",
  "build.js",
  "cmd.md",
  "cnode-mv.md",
  "dat.json",
  "encodeURIComponent_attack.js",
  "gfw.md",
  "github-proxy.md",
  "index.md",
  "love.md",
  "mac.md",
  "mx-2013.md",
  "nae-cli.md",
  "node-v8-flags.md",
  "optimized-test.js",
  "password.md",
  "pipe.js",
  "server.js",
  "simplehttpserver.js",
  "storyjs-embed.js",
  "timeline.js",
  "timeline.css",
  "urlparse_0.6_0.8.js",
  "visa.md",
  "wedding-net4.md",
  ".jshintrc",
  "mvn-install.sh",
];

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  // "pages/posts" is generated by voidBlog on every build/check; never format or lint it.
  fmt: { ignorePatterns: [...legacyIgnorePatterns, "pages/posts"] },
  lint: {
    options: { typeAware: true, typeCheck: true },
    ignorePatterns: [...legacyIgnorePatterns, "pages/posts"],
  },
  optimizeDeps: {
    include: optimizedDeps,
  },
  plugins: [
    voidBlog(blogConfig, { routes: { post: "src/blog/PostRoute.tsx" } }),
    ...voidPlugin(),
    mdx(mdxOptions),
    ...tailwindcss(),
    ...voidReact({
      prefetch: { hoverDelay: 150 },
      viewTransitions: true,
    }),
  ],
  resolve: {
    dedupe: ["react", "react-dom"],
  },
  ssr: {
    optimizeDeps: {
      include: optimizedDeps,
    },
  },
});
