// Auto-generated by @void/md — do not edit

export interface VoidMdPage {
  path: string;
  title: string;
  frontmatter: Record<string, unknown>;
  headings: { depth: number; slug: string; text: string }[];
}

declare const pages: VoidMdPage[];
export default pages;
