// Auto-generated by void — do not edit
export {}
interface StandardSchemaV1<Input = unknown, Output = Input> {
  readonly "~standard": {
    readonly version: 1;
    readonly vendor: string;
    readonly validate: (value: unknown) => unknown;
    readonly types?: { readonly input: Input; readonly output: Output } | undefined;
  };
}
declare namespace StandardSchemaV1 {
  type InferInput<Schema extends StandardSchemaV1> = NonNullable<
    Schema["~standard"]["types"]
  >["input"];
  type InferOutput<Schema extends StandardSchemaV1> = NonNullable<
    Schema["~standard"]["types"]
  >["output"];
}

type Serialize<T> =
  T extends Response ? never :
  T extends Date ? string :
  T extends bigint ? never :
  T extends Function ? never :
  T extends undefined ? never :
  T extends Array<infer U> ? Array<Serialize<U>> :
  T extends object ? { [K in keyof T as T[K] extends Function ? never : K]: Serialize<T[K]> } :
  T;

type ExtractInput<V> = {
  [K in keyof V as V[K] extends StandardSchemaV1 ? K : never]:
    V[K] extends StandardSchemaV1 ? StandardSchemaV1.InferInput<V[K]> : never;
};

type ExtractOutput<S> =
  S extends StandardSchemaV1 ? StandardSchemaV1.InferOutput<S> : never;

type RouteParams<P extends readonly string[]> =
  P extends readonly [] ? Record<string, never> : { [K in P[number]]: string };

declare module "void/routes" {
  export interface RouteMap {}
  export interface WebSocketRouteMap {}
  export interface PageActionMap {}

  export type ParseActionUrl<U extends string> = U extends `${infer Base}?${infer Action}` ? {
    base: Base;
    action: Action;
  } : {
    base: U;
    action: never;
  };

  export type ResolveActionBody<U extends string> =
    ParseActionUrl<U>["base"] extends keyof PageActionMap
      ? ParseActionUrl<U>["action"] extends never
        ? PageActionMap[ParseActionUrl<U>["base"]] extends { body: infer B }
          ? B
          : Record<string, unknown>
        : PageActionMap[ParseActionUrl<U>["base"]] extends { actions: infer A }
          ? ParseActionUrl<U>["action"] extends keyof A
            ? A[ParseActionUrl<U>["action"]] extends { body: infer B }
              ? B
              : Record<string, unknown>
            : never
          : never
      : Record<string, unknown>;

  export type ResolveActionParams<U extends string> =
    ParseActionUrl<U>["base"] extends keyof PageActionMap
      ? PageActionMap[ParseActionUrl<U>["base"]] extends { params: infer P }
        ? P
        : never
      : never;

  export type HasActionParams<U extends string> =
    ResolveActionParams<U> extends Record<string, string> ? true : false;

  export type ActionFormOptions<U extends string> =
    HasActionParams<U> extends true ? { params: ResolveActionParams<U> } : { params?: never };

  export type ActionUrl =
    | {
        [K in keyof PageActionMap]: PageActionMap[K] extends { body: any } ? K : never;
      }[keyof PageActionMap]
    | {
        [K in keyof PageActionMap]: PageActionMap[K] extends { actions: infer A }
          ? `${K & string}?${keyof A & string}`
          : never;
      }[keyof PageActionMap]

  interface RouteMap {
  }

  interface WebSocketRouteMap {
  }
}
