// Auto-generated by void — do not edit
interface StandardSchemaV1<Input = unknown, Output = Input> {
  readonly "~standard": {
    readonly version: 1;
    readonly vendor: string;
    readonly validate: (value: unknown) => unknown;
    readonly types?: { readonly input: Input; readonly output: Output } | undefined;
  };
}
declare namespace StandardSchemaV1 {
  type InferInput<Schema extends StandardSchemaV1> = NonNullable<
    Schema["~standard"]["types"]
  >["input"];
}

type Serialize<T> =
  T extends Response ? never :
  T extends Date ? string :
  T extends bigint ? never :
  T extends Function ? never :
  T extends undefined ? never :
  T extends Array<infer U> ? Array<Serialize<U>> :
  T extends object ? { [K in keyof T as T[K] extends Function ? never : K]: Serialize<T[K]> } :
  T;

type ExtractInput<V> = {
  [K in keyof V as V[K] extends StandardSchemaV1 ? K : never]:
    V[K] extends StandardSchemaV1 ? StandardSchemaV1.InferInput<V[K]> : never;
};

declare module "void/routes" {
  interface RouteMap {
  }
}
