import {
  lazy,
  Suspense,
  type ComponentType,
  type LazyExoticComponent,
} from 'react';
// Generated by void-blog.
import type { BlogPostContent, BlogTableOfContents } from 'void-blog';
import { BlogPostRoute } from 'void-blog/react';
import blogConfig from '../../blog.config.ts';
import type { Props } from './[slug].server.ts';

type MdxModule = Readonly<{
  default: BlogPostContent;
  tableOfContents?: BlogTableOfContents | null;
}>;

type PostRouteComponent =
  | ComponentType<Props>
  | LazyExoticComponent<ComponentType<Props>>;

const serverPosts = import.meta.env.SSR
  ? import.meta.glob<MdxModule>('../../posts/*.mdx', {
      eager: true,
    })
  : ({} as Record<string, MdxModule>);
const clientPosts = import.meta.glob<MdxModule>('../../posts/*.mdx');

const createPostRoute = (mod: MdxModule): ComponentType<Props> =>
  function PostRoute(props) {
    return (
      <BlogPostRoute
        {...props}
        config={blogConfig}
        content={mod.default}
        tableOfContents={mod.tableOfContents ?? null}
      />
    );
  };

const serverRoutes = Object.fromEntries(
  Object.entries(serverPosts).map(([key, mod]) => [key, createPostRoute(mod)]),
) as Record<string, PostRouteComponent>;

const clientRoutes = Object.fromEntries(
  Object.entries(clientPosts).map(([key, loadPost]) => [
    key,
    lazy(async () => {
      const mod = await loadPost();

      return { default: createPostRoute(mod) };
    }),
  ]),
) as Record<string, PostRouteComponent>;

const routes = import.meta.env.SSR ? serverRoutes : clientRoutes;

export default function PostPage(props: Props) {
  const { post } = props;

  if (!post) {
    return null;
  }

  const PostRoute = routes[`../../posts/${post.slug}.mdx`];

  if (!PostRoute) {
    return null;
  }

  return (
    <Suspense fallback={null}>
      <PostRoute {...props} />
    </Suspense>
  );
}
