// Generated by void-blog.
import blogConfig from 'void-blog/blog-config';
import allPosts from 'void-blog/posts';
import {
  createPostHead,
  createPostLoader,
  type BlogPostLoaderProps,
} from 'void-blog/server';

export type Props = BlogPostLoaderProps;

export const prerender = true;

export function getPrerenderPaths() {
  return allPosts.map(({ slug }) => ({ slug }));
}

export const loader = createPostLoader({ posts: allPosts });
export const head = createPostHead(blogConfig);
