name: Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: vpx void deploy
        env:
          VOID_TOKEN: ${{ secrets.VOID_TOKEN }}
